# Question 1: Basic List Operations

In [1]:
fruits= ["apple", "banana", "orange", "grape", "kiwi"]

print(fruits)

['apple', 'banana', 'orange', 'grape', 'kiwi']


In [2]:
fruits= ["apple", "banana", "orange", "grape", "kiwi"]

fruits.append("pear")
print(fruits)

['apple', 'banana', 'orange', 'grape', 'kiwi', 'pear']


In [4]:
fruits= ['apple', 'banana', 'orange', 'grape', 'kiwi', 'pear']

fruits.insert(1,"mango")
print(fruits)

['apple', 'mango', 'banana', 'orange', 'grape', 'kiwi', 'pear']


In [5]:
fruits.remove("orange")
print(fruits)

['apple', 'mango', 'banana', 'grape', 'kiwi', 'pear']


# Question 2: Slicing and Indexing

In [8]:
numbers= list(range(0,10))

print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
numbers[3]

3

In [12]:
print(numbers[2:7])

[2, 3, 4, 5, 6]


In [13]:
print(numbers[-3:])

[7, 8, 9]


# Question 3: List Comprehension

In [14]:
squares = [ x**2 for x in range(1,11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [15]:
even_squares = [x for x in squares if x % 2 == 0]
print(even_squares)

[4, 16, 36, 64, 100]


# Question 4: List Manipulation

In [16]:
colors = ["red", "green", "blue", "yellow", "purple"]
print(colors)

['red', 'green', 'blue', 'yellow', 'purple']


In [17]:
colors[0], colors[-1] = colors[-1], colors[0]
colors

['purple', 'green', 'blue', 'yellow', 'red']

In [18]:
colors = ["red", "green", "blue", "yellow", "purple"]
colors.reverse()
colors

['purple', 'yellow', 'blue', 'green', 'red']

In [19]:
colors = ["red", "green", "blue", "yellow", "purple"]
del colors[1:3]
print(colors)

['red', 'yellow', 'purple']


# Question 5: Advanced Slicing

In [1]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [2]:
first_half = (letters[0:5])
print(first_half)

['a', 'b', 'c', 'd', 'e']


In [4]:
last_three = (letters[-3:])
print(last_three)

['h', 'i', 'j']


# Question 6: Nested Lists

In [5]:
import numpy as np

matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
element = matrix[1,2]
print(element)

6


In [7]:
matrix[1,0] = 0
print(matrix)

[[1 2 3]
 [0 5 6]
 [7 8 9]]
